jobs:
  run-macro:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Show files
        run: ls -la

      - name: Show data_fetcher
        run: cat data_fetcher.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run macro model
        run: python daily_job.py

